// Package main provides end-to-end tests for the gormdb2struct tool.
package main

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/dan-sherwin/gormdb2struct/internal/config"
	"github.com/dan-sherwin/gormdb2struct/internal/generator"
	"gorm.io/gen"
)

// TestPostgresDbInitTemplateNoDB validates the Postgres DbInit code generation
// without connecting to any Postgres server by fabricating a generator with
// fake model names and invoking generatePostgresDbInit directly.
func TestPostgresDbInitTemplateNoDB(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping postgres template test in short mode")
	}

	// Create an OutPath under the project root so that package name resolution is simple.
	outPath := filepath.Join(projectRootPG(t), "generated_pg_nodb")
	if err := os.MkdirAll(outPath, 0o755); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(outPath) })

	// Create a minimal gen.Generator and populate its Data map with fake model names.
	g := gen.NewGenerator(gen.Config{
		OutPath:      outPath,
		ModelPkgPath: filepath.Join(outPath, "models"),
	})
	// NewGenerator already initializes g.Data (map[string]*genInfo). We only need keys; values can be nil.
	g.Data["Foo"] = nil
	g.Data["Bar"] = nil

	// Prepare a minimal Postgres config with IncludeAutoMigrate enabled.
	cfg := config.Config{
		DbInit: config.GenerateDbInitConfig{
			IncludeAutoMigrate: true,
		},
		DbHost:     "db.example.local",
		DbPort:     5432,
		DbName:     "unit_test_db",
		DbUser:     "test_user",
		DbPassword: "secret",
		DbSSLMode:  false,
	}

	// Generate the db.go initializer using the template function.
	if err := generator.WritePostgresDBInit(cfg, g); err != nil {
		t.Fatalf("write postgres DbInit: %v", err)
	}

	// Verify the output file was created.
	outFile := filepath.Join(outPath, "db.go")
	b, err := os.ReadFile(outFile)
	if err != nil {
		t.Fatalf("reading generated db.go: %v", err)
	}
	content := string(b)

	pkgBase := filepath.Base(outPath)

	// Assertions on generated content.
	mustContain(t, content, "Code generated by gormdb2struct; DO NOT EDIT.")
	mustContain(t, content, "package "+pkgBase)
	mustContain(t, content, "\""+modulePathPG(t)+"/"+pkgBase+"/models\"")
	// Ensure AutoMigrate contains our fake models
	mustContain(t, content, "&models.Foo{}")
	mustContain(t, content, "&models.Bar{}")
	// Ensure DSN is constructed via go-utilities when optional DSN is not provided.
	mustContain(t, content, "utilities.DbDSN(utilities.DbDSNConfig{")
	mustContain(t, content, "\"github.com/dan-sherwin/go-utilities\"")
	mustNotContain(t, content, "type DbDSNConfig struct")
	mustNotContain(t, content, "func DbDSN(")
	mustNotContain(t, content, "slog.")
}

func TestPostgresDbInitTemplateOptionalAppSettingsAndSlogGorm(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping postgres template test in short mode")
	}

	outPath := filepath.Join(projectRootPG(t), "generated_pg_nodb_opts")
	if err := os.MkdirAll(outPath, 0o755); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(outPath) })

	g := gen.NewGenerator(gen.Config{
		OutPath:      outPath,
		ModelPkgPath: filepath.Join(outPath, "models"),
	})
	g.Data["Foo"] = nil

	cfg := config.Config{
		DbInit: config.GenerateDbInitConfig{
			GenerateAppSettingsRegistration: true,
			UseSlogGormLogger:               true,
		},
		DbHost:     "db.example.local",
		DbPort:     5432,
		DbName:     "unit_test_db",
		DbUser:     "test_user",
		DbPassword: "secret",
		DbSSLMode:  true,
	}

	if err := generator.WritePostgresDBInit(cfg, g); err != nil {
		t.Fatalf("write postgres DbInit with optional features: %v", err)
	}

	b, err := os.ReadFile(filepath.Join(outPath, "db.go"))
	if err != nil {
		t.Fatalf("reading generated db.go: %v", err)
	}
	content := string(b)

	mustContain(t, content, `app_settings.RegisterStringSetting("dbHost", "Hostname of the database", &DbHost)`)
	mustContain(t, content, `app_settings.RegisterIntSetting("dbPort", "Port of the database", &DbPort)`)
	mustContain(t, content, `app_settings.RegisterBoolSetting("dbSSLMode", "Whether to require SSL for the database connection", &DbSSLMode)`)
	mustContain(t, content, `"github.com/dan-sherwin/go-app-settings"`)
	mustContain(t, content, `"github.com/orandin/slog-gorm"`)
	mustContain(t, content, "Logger: slogGorm.New(),")
}

func mustContain(t *testing.T, s, sub string) {
	t.Helper()
	if !strings.Contains(s, sub) {
		t.Fatalf("expected generated content to contain %q, but it did not", sub)
	}
}

func mustNotContain(t *testing.T, s, sub string) {
	t.Helper()
	if strings.Contains(s, sub) {
		t.Fatalf("expected generated content not to contain %q, but it did", sub)
	}
}

// projectRootPG returns the repo root directory (same strategy as the SQLite test)
func projectRootPG(_ *testing.T) string {
	_, file, _, _ := runtime.Caller(0)
	return filepath.Dir(file)
}

func modulePathPG(t *testing.T) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(projectRootPG(t), "go.mod"))
	if err != nil {
		t.Fatal(err)
	}
	for _, ln := range strings.Split(string(b), "\n") {
		ln = strings.TrimSpace(ln)
		if strings.HasPrefix(ln, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(ln, "module "))
		}
	}
	t.Fatal("module path not found")
	return ""
}
