package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"text/template"

	"github.com/iancoleman/strcase"
)

type generatedDomainTemplateData struct {
	PackageName       string
	DBType            string
	GoType            string
	UnderlyingGoType  string
	Imports           []string
	ConstraintComment []string
	RegexPattern      string
	RegexVarName      string
}

func writeGeneratedTypesPackage(pkg generatedTypesPackage) error {
	if err := os.MkdirAll(pkg.OutputDir, 0o755); err != nil {
		return fmt.Errorf("create generated types output directory %s: %w", pkg.OutputDir, err)
	}

	if err := writeGeneratedTypesHelperFile(pkg); err != nil {
		return err
	}
	for _, enumType := range pkg.Enums {
		if err := writeGeneratedEnumFile(pkg, enumType); err != nil {
			return err
		}
	}
	for _, domainType := range pkg.Domains {
		if err := writeGeneratedDomainFile(pkg, domainType); err != nil {
			return err
		}
	}
	for _, arrayType := range pkg.Arrays {
		if err := writeGeneratedArrayFile(pkg, arrayType); err != nil {
			return err
		}
	}

	return nil
}

func writeGeneratedTypesHelperFile(pkg generatedTypesPackage) error {
	rendered, err := renderTemplate("generated_types_helpers", generatedTypesHelpersTemplate, struct {
		PackageName string
	}{
		PackageName: pkg.PackageName,
	})
	if err != nil {
		return err
	}

	outFile := filepath.Join(pkg.OutputDir, "zz_generated_helpers.gen.go")
	if err := writeFormattedGoFile(outFile, rendered); err != nil {
		return err
	}

	return nil
}

func writeGeneratedEnumFile(pkg generatedTypesPackage, enumType generatedEnumType) error {
	rendered, err := renderTemplate("generated_enum_type", generatedEnumTemplate, struct {
		PackageName string
		generatedEnumType
	}{
		PackageName:       pkg.PackageName,
		generatedEnumType: enumType,
	})
	if err != nil {
		return err
	}

	outFile := filepath.Join(pkg.OutputDir, enumType.FileName)
	if err := writeFormattedGoFile(outFile, rendered); err != nil {
		return err
	}

	return nil
}

func writeGeneratedDomainFile(pkg generatedTypesPackage, domainType generatedDomainType) error {
	imports := append([]string{
		"database/sql/driver",
		"fmt",
		"gorm.io/gorm",
		"gorm.io/gorm/schema",
	}, domainType.Imports...)
	if domainType.RegexPattern != "" {
		imports = append(imports, "regexp")
	}
	imports = uniqueStrings(imports)
	sort.Strings(imports)

	commentLines := make([]string, 0, len(domainType.Constraints))
	for _, constraint := range domainType.Constraints {
		commentLines = append(commentLines, "Source constraint: "+constraint)
	}

	rendered, err := renderTemplate("generated_domain_type", generatedDomainTemplate, generatedDomainTemplateData{
		PackageName:       pkg.PackageName,
		DBType:            domainType.DBType,
		GoType:            domainType.GoType,
		UnderlyingGoType:  domainType.UnderlyingGoType,
		Imports:           imports,
		ConstraintComment: commentLines,
		RegexPattern:      domainType.RegexPattern,
		RegexVarName:      strcase.ToLowerCamel(domainType.GoType) + "Pattern",
	})
	if err != nil {
		return err
	}

	outFile := filepath.Join(pkg.OutputDir, domainType.FileName)
	if err := writeFormattedGoFile(outFile, rendered); err != nil {
		return err
	}

	return nil
}

func writeGeneratedArrayFile(pkg generatedTypesPackage, arrayType generatedArrayType) error {
	rendered, err := renderTemplate("generated_array_type", generatedArrayTemplate, struct {
		PackageName string
		generatedArrayType
	}{
		PackageName:        pkg.PackageName,
		generatedArrayType: arrayType,
	})
	if err != nil {
		return err
	}

	outFile := filepath.Join(pkg.OutputDir, arrayType.FileName)
	if err := writeFormattedGoFile(outFile, rendered); err != nil {
		return err
	}

	return nil
}

func renderTemplate(name, tmpl string, data any) ([]byte, error) {
	parsed, err := template.New(name).Parse(tmpl)
	if err != nil {
		return nil, fmt.Errorf("parse %s template: %w", name, err)
	}

	var buf bytes.Buffer
	if err := parsed.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("render %s template: %w", name, err)
	}

	return buf.Bytes(), nil
}

func writeFormattedGoFile(outFile string, src []byte) error {
	formatted, err := format.Source(src)
	if err != nil {
		return fmt.Errorf("format generated Go file %s: %w", outFile, err)
	}
	if err := os.WriteFile(outFile, formatted, 0o644); err != nil {
		return fmt.Errorf("write generated Go file %s: %w", outFile, err)
	}
	return nil
}

const generatedEnumTemplate = `// Code generated by gormdb2struct; DO NOT EDIT.
package {{.PackageName}}

import (
	"database/sql/driver"
	"fmt"

	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

// {{.GoType}} represents the PostgreSQL {{printf "%q" .DBType}} enum.
type {{.GoType}} string

const (
{{- range .Constants}}
	{{.Name}} {{$.GoType}} = {{printf "%q" .Value}}
{{- end}}
)

// {{.GoType}}Values returns the supported values for {{.GoType}}.
func {{.GoType}}Values() []{{.GoType}} {
	return []{{.GoType}}{
{{- range .Constants}}
		{{.Name}},
{{- end}}
	}
}

// Validate returns an error when the enum value is not one of the configured PostgreSQL labels.
func (v {{.GoType}}) Validate() error {
	switch v {
	case {{range $index, $constant := .Constants}}{{if $index}}, {{end}}{{$constant.Name}}{{end}}:
		return nil
	default:
		return fmt.Errorf("invalid {{.GoType}}: %q", string(v))
	}
}

// IsValid reports whether the enum value is valid.
func (v {{.GoType}}) IsValid() bool {
	return v.Validate() == nil
}

// String returns the string representation of the enum.
func (v {{.GoType}}) String() string {
	return string(v)
}

// Value implements driver.Valuer.
func (v {{.GoType}}) Value() (driver.Value, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return string(v), nil
}

// Scan implements sql.Scanner.
func (v *{{.GoType}}) Scan(value any) error {
	var raw string
	if err := generatedScanInto(&raw, value); err != nil {
		return err
	}
	candidate := {{.GoType}}(raw)
	if raw != "" {
		if err := candidate.Validate(); err != nil {
			return err
		}
	}
	*v = candidate
	return nil
}

// MarshalJSON implements json.Marshaler.
func (v {{.GoType}}) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return generatedMarshalJSONValue(string(v))
}

// UnmarshalJSON implements json.Unmarshaler.
func (v *{{.GoType}}) UnmarshalJSON(data []byte) error {
	var raw string
	if err := generatedUnmarshalJSONValue(data, &raw); err != nil {
		return err
	}
	candidate := {{.GoType}}(raw)
	if raw != "" {
		if err := candidate.Validate(); err != nil {
			return err
		}
	}
	*v = candidate
	return nil
}

// MarshalText implements encoding.TextMarshaler.
func (v {{.GoType}}) MarshalText() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return generatedMarshalTextValue(string(v))
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (v *{{.GoType}}) UnmarshalText(data []byte) error {
	var raw string
	if err := generatedUnmarshalTextValue(data, &raw); err != nil {
		return err
	}
	candidate := {{.GoType}}(raw)
	if raw != "" {
		if err := candidate.Validate(); err != nil {
			return err
		}
	}
	*v = candidate
	return nil
}

// GormDataType returns the generic GORM data type.
func ({{.GoType}}) GormDataType() string {
	return {{printf "%q" .DBType}}
}

// GormDBDataType returns the PostgreSQL database type.
func ({{.GoType}}) GormDBDataType(db *gorm.DB, _ *schema.Field) string {
	if db.Name() == "postgres" {
		return {{printf "%q" .DBType}}
	}
	return ""
}
`

const generatedDomainTemplate = `// Code generated by gormdb2struct; DO NOT EDIT.
package {{.PackageName}}

import (
{{- range .Imports}}
	{{printf "%q" .}}
{{- end}}
)

{{- range .ConstraintComment}}
// {{.}}
{{- end}}
// {{.GoType}} wraps PostgreSQL domain {{printf "%q" .DBType}}.
type {{.GoType}} {{.UnderlyingGoType}}

{{- if .RegexPattern}}
var {{.RegexVarName}} = regexp.MustCompile({{printf "%q" .RegexPattern}})
{{- end}}

// Underlying returns the wrapped Go value.
func (v {{.GoType}}) Underlying() {{.UnderlyingGoType}} {
	return {{.UnderlyingGoType}}(v)
}

// String returns a string representation of the wrapped value.
func (v {{.GoType}}) String() string {
	text, err := generatedMarshalTextValue({{.UnderlyingGoType}}(v))
	if err == nil {
		return string(text)
	}
	return fmt.Sprint({{.UnderlyingGoType}}(v))
}

// Validate enforces any recognized domain constraints.
func (v {{.GoType}}) Validate() error {
{{- if .RegexPattern}}
	text, err := generatedMarshalTextValue({{.UnderlyingGoType}}(v))
	if err != nil {
		return err
	}
	if !{{.RegexVarName}}.Match(text) {
		return fmt.Errorf("invalid {{.GoType}}: %q", string(text))
	}
{{- end}}
	return nil
}

// IsValid reports whether the wrapped value satisfies the generated validation.
func (v {{.GoType}}) IsValid() bool {
	return v.Validate() == nil
}

// Value implements driver.Valuer.
func (v {{.GoType}}) Value() (driver.Value, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return generatedValueOf({{.UnderlyingGoType}}(v))
}

// Scan implements sql.Scanner.
func (v *{{.GoType}}) Scan(value any) error {
	var raw {{.UnderlyingGoType}}
	if err := generatedScanInto(&raw, value); err != nil {
		return err
	}
	candidate := {{.GoType}}(raw)
	if err := candidate.Validate(); err != nil {
		return err
	}
	*v = candidate
	return nil
}

// MarshalJSON implements json.Marshaler.
func (v {{.GoType}}) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return generatedMarshalJSONValue({{.UnderlyingGoType}}(v))
}

// UnmarshalJSON implements json.Unmarshaler.
func (v *{{.GoType}}) UnmarshalJSON(data []byte) error {
	var raw {{.UnderlyingGoType}}
	if err := generatedUnmarshalJSONValue(data, &raw); err != nil {
		return err
	}
	candidate := {{.GoType}}(raw)
	if err := candidate.Validate(); err != nil {
		return err
	}
	*v = candidate
	return nil
}

// MarshalText implements encoding.TextMarshaler.
func (v {{.GoType}}) MarshalText() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return generatedMarshalTextValue({{.UnderlyingGoType}}(v))
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (v *{{.GoType}}) UnmarshalText(data []byte) error {
	var raw {{.UnderlyingGoType}}
	if err := generatedUnmarshalTextValue(data, &raw); err != nil {
		return err
	}
	candidate := {{.GoType}}(raw)
	if err := candidate.Validate(); err != nil {
		return err
	}
	*v = candidate
	return nil
}

// GormDataType returns the generic GORM data type.
func ({{.GoType}}) GormDataType() string {
	return {{printf "%q" .DBType}}
}

// GormDBDataType returns the PostgreSQL database type.
func ({{.GoType}}) GormDBDataType(db *gorm.DB, _ *schema.Field) string {
	if db.Name() == "postgres" {
		return {{printf "%q" .DBType}}
	}
	return ""
}
`

const generatedArrayTemplate = `// Code generated by gormdb2struct; DO NOT EDIT.
package {{.PackageName}}

import (
	"database/sql/driver"
	"fmt"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

// {{.GoType}} represents the PostgreSQL {{printf "%q" .DBType}} array type.
type {{.GoType}} []{{.ElementGoType}}

// Validate ensures every element is valid.
func (v {{.GoType}}) Validate() error {
	for _, element := range v {
		if err := element.Validate(); err != nil {
			return fmt.Errorf("invalid {{.ElementGoType}} in {{.GoType}}: %w", err)
		}
	}
	return nil
}

// Value implements driver.Valuer.
func (v {{.GoType}}) Value() (driver.Value, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	if len(v) == 0 {
		return "{}", nil
	}

	values := make([]string, len(v))
	for i, element := range v {
		values[i] = element.String()
	}
	return generatedFormatPostgresTextArray(values), nil
}

// Scan implements sql.Scanner.
func (v *{{.GoType}}) Scan(src any) error {
	values, err := generatedParsePostgresTextArray(src)
	if err != nil {
		return err
	}
	if values == nil {
		*v = nil
		return nil
	}
	if len(values) == 0 {
		*v = {{.GoType}}{}
		return nil
	}

	result := make({{.GoType}}, len(values))
	for i, raw := range values {
		candidate := {{.ElementGoType}}(raw)
		if err := candidate.Validate(); err != nil {
			return fmt.Errorf("invalid {{.ElementGoType}} in {{.GoType}}: %w", err)
		}
		result[i] = candidate
	}

	*v = result
	return nil
}

// MarshalJSON implements json.Marshaler.
func (v {{.GoType}}) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return generatedMarshalJSONValue([]{{.ElementGoType}}(v))
}

// UnmarshalJSON implements json.Unmarshaler.
func (v *{{.GoType}}) UnmarshalJSON(data []byte) error {
	var values []{{.ElementGoType}}
	if err := generatedUnmarshalJSONValue(data, &values); err != nil {
		return err
	}
	candidate := {{.GoType}}(values)
	if err := candidate.Validate(); err != nil {
		return err
	}
	*v = candidate
	return nil
}

// MarshalText implements encoding.TextMarshaler.
func (v {{.GoType}}) MarshalText() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	values := make([]string, len(v))
	for i, element := range v {
		values[i] = element.String()
	}
	return generatedMarshalTextValue(strings.Join(values, ","))
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (v *{{.GoType}}) UnmarshalText(data []byte) error {
	if len(data) == 0 {
		*v = nil
		return nil
	}
	parts := strings.Split(string(data), ",")
	result := make({{.GoType}}, 0, len(parts))
	for _, raw := range parts {
		candidate := {{.ElementGoType}}(strings.TrimSpace(raw))
		if err := candidate.Validate(); err != nil {
			return fmt.Errorf("invalid {{.ElementGoType}} in {{.GoType}}: %w", err)
		}
		result = append(result, candidate)
	}
	*v = result
	return nil
}

// GormDataType returns the generic GORM data type.
func ({{.GoType}}) GormDataType() string {
	return {{printf "%q" .DBType}}
}

// GormDBDataType returns the PostgreSQL database type.
func ({{.GoType}}) GormDBDataType(db *gorm.DB, _ *schema.Field) string {
	if db.Name() == "postgres" {
		return {{printf "%q" .DBType}}
	}
	return ""
}
`

const generatedTypesHelpersTemplate = `// Code generated by gormdb2struct; DO NOT EDIT.
package {{.PackageName}}

import (
	"database/sql"
	"database/sql/driver"
	"encoding"
	"encoding/json"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"time"
)

func generatedScanInto(dst any, value any) error {
	if dst == nil {
		return fmt.Errorf("generated type scan destination is nil")
	}

	rv := reflect.ValueOf(dst)
	if rv.Kind() != reflect.Pointer || rv.IsNil() {
		return fmt.Errorf("generated type scan destination must be a non-nil pointer, got %T", dst)
	}

	if value == nil {
		rv.Elem().SetZero()
		return nil
	}

	if scanner, ok := dst.(sql.Scanner); ok {
		return scanner.Scan(value)
	}

	elem := rv.Elem()
	switch {
	case elem.Type() == reflect.TypeOf(time.Time{}):
		parsed, err := generatedToTime(value)
		if err != nil {
			return err
		}
		elem.Set(reflect.ValueOf(parsed))
		return nil
	case elem.Kind() == reflect.String:
		parsed, err := generatedToString(value)
		if err != nil {
			return err
		}
		elem.SetString(parsed)
		return nil
	case elem.Kind() == reflect.Bool:
		parsed, err := generatedToBool(value)
		if err != nil {
			return err
		}
		elem.SetBool(parsed)
		return nil
	case elem.Kind() >= reflect.Int && elem.Kind() <= reflect.Int64:
		parsed, err := generatedToInt64(value)
		if err != nil {
			return err
		}
		if elem.OverflowInt(parsed) {
			return fmt.Errorf("generated type scan overflow for %s: %d", elem.Type(), parsed)
		}
		elem.SetInt(parsed)
		return nil
	case elem.Kind() >= reflect.Uint && elem.Kind() <= reflect.Uint64:
		parsed, err := generatedToUint64(value)
		if err != nil {
			return err
		}
		if elem.OverflowUint(parsed) {
			return fmt.Errorf("generated type scan overflow for %s: %d", elem.Type(), parsed)
		}
		elem.SetUint(parsed)
		return nil
	case elem.Kind() == reflect.Float32 || elem.Kind() == reflect.Float64:
		parsed, err := generatedToFloat64(value)
		if err != nil {
			return err
		}
		if elem.OverflowFloat(parsed) {
			return fmt.Errorf("generated type scan overflow for %s: %f", elem.Type(), parsed)
		}
		elem.SetFloat(parsed)
		return nil
	case elem.Kind() == reflect.Slice && elem.Type().Elem().Kind() == reflect.Uint8:
		parsed, err := generatedToBytes(value)
		if err != nil {
			return err
		}
		elem.SetBytes(parsed)
		return nil
	}

	return fmt.Errorf("unsupported generated type scan into %T from %T", dst, value)
}

func generatedValueOf(value any) (driver.Value, error) {
	if value == nil {
		return nil, nil
	}
	if valuer, ok := value.(driver.Valuer); ok {
		return valuer.Value()
	}

	rv := reflect.ValueOf(value)
	if !rv.IsValid() {
		return nil, nil
	}

	switch {
	case rv.Type() == reflect.TypeOf(time.Time{}):
		return rv.Interface().(time.Time), nil
	case rv.Kind() == reflect.String:
		return rv.String(), nil
	case rv.Kind() == reflect.Bool:
		return rv.Bool(), nil
	case rv.Kind() >= reflect.Int && rv.Kind() <= reflect.Int64:
		return rv.Int(), nil
	case rv.Kind() >= reflect.Uint && rv.Kind() <= reflect.Uint64:
		const maxInt64 = ^uint64(0) >> 1
		if rv.Uint() > maxInt64 {
			return nil, fmt.Errorf("generated type value overflows int64: %d", rv.Uint())
		}
		return int64(rv.Uint()), nil
	case rv.Kind() == reflect.Float32 || rv.Kind() == reflect.Float64:
		return rv.Float(), nil
	case rv.Kind() == reflect.Slice && rv.Type().Elem().Kind() == reflect.Uint8:
		return append([]byte(nil), rv.Bytes()...), nil
	}

	return nil, fmt.Errorf("unsupported generated type value %T", value)
}

func generatedMarshalJSONValue(value any) ([]byte, error) {
	if marshaler, ok := value.(json.Marshaler); ok {
		return marshaler.MarshalJSON()
	}
	return json.Marshal(value)
}

func generatedUnmarshalJSONValue(data []byte, dst any) error {
	if unmarshaler, ok := dst.(json.Unmarshaler); ok {
		return unmarshaler.UnmarshalJSON(data)
	}
	return json.Unmarshal(data, dst)
}

func generatedMarshalTextValue(value any) ([]byte, error) {
	if marshaler, ok := value.(encoding.TextMarshaler); ok {
		return marshaler.MarshalText()
	}

	rv := reflect.ValueOf(value)
	if !rv.IsValid() {
		return nil, nil
	}

	switch {
	case rv.Type() == reflect.TypeOf(time.Time{}):
		return []byte(rv.Interface().(time.Time).Format(time.RFC3339Nano)), nil
	case rv.Kind() == reflect.String:
		return []byte(rv.String()), nil
	case rv.Kind() == reflect.Bool:
		return strconv.AppendBool(nil, rv.Bool()), nil
	case rv.Kind() >= reflect.Int && rv.Kind() <= reflect.Int64:
		return []byte(strconv.FormatInt(rv.Int(), 10)), nil
	case rv.Kind() >= reflect.Uint && rv.Kind() <= reflect.Uint64:
		return []byte(strconv.FormatUint(rv.Uint(), 10)), nil
	case rv.Kind() == reflect.Float32:
		return []byte(strconv.FormatFloat(rv.Float(), 'f', -1, 32)), nil
	case rv.Kind() == reflect.Float64:
		return []byte(strconv.FormatFloat(rv.Float(), 'f', -1, 64)), nil
	case rv.Kind() == reflect.Slice && rv.Type().Elem().Kind() == reflect.Uint8:
		return append([]byte(nil), rv.Bytes()...), nil
	default:
		return []byte(fmt.Sprint(value)), nil
	}
}

func generatedUnmarshalTextValue(data []byte, dst any) error {
	if dst == nil {
		return fmt.Errorf("generated type text destination is nil")
	}
	if unmarshaler, ok := dst.(encoding.TextUnmarshaler); ok {
		return unmarshaler.UnmarshalText(data)
	}

	rv := reflect.ValueOf(dst)
	if rv.Kind() != reflect.Pointer || rv.IsNil() {
		return fmt.Errorf("generated type text destination must be a non-nil pointer, got %T", dst)
	}
	if len(data) == 0 {
		rv.Elem().SetZero()
		return nil
	}

	elem := rv.Elem()
	switch {
	case elem.Type() == reflect.TypeOf(time.Time{}):
		parsed, err := generatedParseTimeString(string(data))
		if err != nil {
			return err
		}
		elem.Set(reflect.ValueOf(parsed))
		return nil
	case elem.Kind() == reflect.String:
		elem.SetString(string(data))
		return nil
	case elem.Kind() == reflect.Bool:
		parsed, err := strconv.ParseBool(strings.TrimSpace(string(data)))
		if err != nil {
			return fmt.Errorf("cannot parse %q as bool: %w", string(data), err)
		}
		elem.SetBool(parsed)
		return nil
	case elem.Kind() >= reflect.Int && elem.Kind() <= reflect.Int64:
		parsed, err := strconv.ParseInt(strings.TrimSpace(string(data)), 10, 64)
		if err != nil {
			return fmt.Errorf("cannot parse %q as int: %w", string(data), err)
		}
		if elem.OverflowInt(parsed) {
			return fmt.Errorf("generated type text overflow for %s: %d", elem.Type(), parsed)
		}
		elem.SetInt(parsed)
		return nil
	case elem.Kind() >= reflect.Uint && elem.Kind() <= reflect.Uint64:
		parsed, err := strconv.ParseUint(strings.TrimSpace(string(data)), 10, 64)
		if err != nil {
			return fmt.Errorf("cannot parse %q as uint: %w", string(data), err)
		}
		if elem.OverflowUint(parsed) {
			return fmt.Errorf("generated type text overflow for %s: %d", elem.Type(), parsed)
		}
		elem.SetUint(parsed)
		return nil
	case elem.Kind() == reflect.Float32 || elem.Kind() == reflect.Float64:
		parsed, err := strconv.ParseFloat(strings.TrimSpace(string(data)), 64)
		if err != nil {
			return fmt.Errorf("cannot parse %q as float: %w", string(data), err)
		}
		if elem.OverflowFloat(parsed) {
			return fmt.Errorf("generated type text overflow for %s: %f", elem.Type(), parsed)
		}
		elem.SetFloat(parsed)
		return nil
	case elem.Kind() == reflect.Slice && elem.Type().Elem().Kind() == reflect.Uint8:
		elem.SetBytes(append([]byte(nil), data...))
		return nil
	}

	return fmt.Errorf("unsupported generated type text destination %T", dst)
}

func generatedToString(value any) (string, error) {
	switch v := value.(type) {
	case string:
		return v, nil
	case []byte:
		return string(v), nil
	default:
		return "", fmt.Errorf("cannot convert %T to string", value)
	}
}

func generatedToBytes(value any) ([]byte, error) {
	switch v := value.(type) {
	case []byte:
		return append([]byte(nil), v...), nil
	case string:
		return []byte(v), nil
	default:
		return nil, fmt.Errorf("cannot convert %T to []byte", value)
	}
}

func generatedToBool(value any) (bool, error) {
	switch v := value.(type) {
	case bool:
		return v, nil
	case string:
		parsed, err := strconv.ParseBool(strings.TrimSpace(v))
		if err != nil {
			return false, fmt.Errorf("cannot parse %q as bool: %w", v, err)
		}
		return parsed, nil
	case []byte:
		return generatedToBool(string(v))
	default:
		return false, fmt.Errorf("cannot convert %T to bool", value)
	}
}

func generatedToInt64(value any) (int64, error) {
	switch v := value.(type) {
	case int:
		return int64(v), nil
	case int8:
		return int64(v), nil
	case int16:
		return int64(v), nil
	case int32:
		return int64(v), nil
	case int64:
		return v, nil
	case uint:
		return int64(v), nil
	case uint8:
		return int64(v), nil
	case uint16:
		return int64(v), nil
	case uint32:
		return int64(v), nil
	case uint64:
		const maxInt64 = ^uint64(0) >> 1
		if v > maxInt64 {
			return 0, fmt.Errorf("cannot convert %d to int64 without overflow", v)
		}
		return int64(v), nil
	case float32:
		return int64(v), nil
	case float64:
		return int64(v), nil
	case string:
		parsed, err := strconv.ParseInt(strings.TrimSpace(v), 10, 64)
		if err != nil {
			return 0, fmt.Errorf("cannot parse %q as int64: %w", v, err)
		}
		return parsed, nil
	case []byte:
		return generatedToInt64(string(v))
	default:
		return 0, fmt.Errorf("cannot convert %T to int64", value)
	}
}

func generatedToUint64(value any) (uint64, error) {
	switch v := value.(type) {
	case uint:
		return uint64(v), nil
	case uint8:
		return uint64(v), nil
	case uint16:
		return uint64(v), nil
	case uint32:
		return uint64(v), nil
	case uint64:
		return v, nil
	case int:
		if v < 0 {
			return 0, fmt.Errorf("cannot convert %d to uint64", v)
		}
		return uint64(v), nil
	case int8:
		if v < 0 {
			return 0, fmt.Errorf("cannot convert %d to uint64", v)
		}
		return uint64(v), nil
	case int16:
		if v < 0 {
			return 0, fmt.Errorf("cannot convert %d to uint64", v)
		}
		return uint64(v), nil
	case int32:
		if v < 0 {
			return 0, fmt.Errorf("cannot convert %d to uint64", v)
		}
		return uint64(v), nil
	case int64:
		if v < 0 {
			return 0, fmt.Errorf("cannot convert %d to uint64", v)
		}
		return uint64(v), nil
	case float32:
		if v < 0 {
			return 0, fmt.Errorf("cannot convert %f to uint64", v)
		}
		return uint64(v), nil
	case float64:
		if v < 0 {
			return 0, fmt.Errorf("cannot convert %f to uint64", v)
		}
		return uint64(v), nil
	case string:
		parsed, err := strconv.ParseUint(strings.TrimSpace(v), 10, 64)
		if err != nil {
			return 0, fmt.Errorf("cannot parse %q as uint64: %w", v, err)
		}
		return parsed, nil
	case []byte:
		return generatedToUint64(string(v))
	default:
		return 0, fmt.Errorf("cannot convert %T to uint64", value)
	}
}

func generatedToFloat64(value any) (float64, error) {
	switch v := value.(type) {
	case float32:
		return float64(v), nil
	case float64:
		return v, nil
	case int:
		return float64(v), nil
	case int8:
		return float64(v), nil
	case int16:
		return float64(v), nil
	case int32:
		return float64(v), nil
	case int64:
		return float64(v), nil
	case uint:
		return float64(v), nil
	case uint8:
		return float64(v), nil
	case uint16:
		return float64(v), nil
	case uint32:
		return float64(v), nil
	case uint64:
		return float64(v), nil
	case string:
		parsed, err := strconv.ParseFloat(strings.TrimSpace(v), 64)
		if err != nil {
			return 0, fmt.Errorf("cannot parse %q as float64: %w", v, err)
		}
		return parsed, nil
	case []byte:
		return generatedToFloat64(string(v))
	default:
		return 0, fmt.Errorf("cannot convert %T to float64", value)
	}
}

func generatedToTime(value any) (time.Time, error) {
	switch v := value.(type) {
	case time.Time:
		return v, nil
	case string:
		return generatedParseTimeString(v)
	case []byte:
		return generatedParseTimeString(string(v))
	default:
		return time.Time{}, fmt.Errorf("cannot convert %T to time.Time", value)
	}
}

func generatedParseTimeString(value string) (time.Time, error) {
	layouts := []string{
		time.RFC3339Nano,
		time.RFC3339,
		"2006-01-02 15:04:05.999999999-07:00",
		"2006-01-02 15:04:05.999999999",
		"2006-01-02 15:04:05",
		"2006-01-02",
	}

	trimmed := strings.TrimSpace(value)
	for _, layout := range layouts {
		if parsed, err := time.Parse(layout, trimmed); err == nil {
			return parsed, nil
		}
	}
	return time.Time{}, fmt.Errorf("cannot parse %q as time.Time", value)
}

func generatedParsePostgresTextArray(src any) ([]string, error) {
	if src == nil {
		return nil, nil
	}

	var input string
	switch v := src.(type) {
	case string:
		input = v
	case []byte:
		input = string(v)
	default:
		return nil, fmt.Errorf("cannot scan %T into PostgreSQL text array", src)
	}

	if input == "" {
		return []string{}, nil
	}
	if len(input) < 2 || input[0] != '{' || input[len(input)-1] != '}' {
		return nil, fmt.Errorf("invalid PostgreSQL array literal %q", input)
	}

	input = input[1 : len(input)-1]
	if input == "" {
		return []string{}, nil
	}

	values := make([]string, 0, strings.Count(input, ",")+1)
	var current strings.Builder
	inQuotes := false
	escaped := false

	for i := 0; i < len(input); i++ {
		ch := input[i]
		if escaped {
			current.WriteByte(ch)
			escaped = false
			continue
		}

		if inQuotes {
			switch ch {
			case '\\':
				escaped = true
			case '"':
				inQuotes = false
			default:
				current.WriteByte(ch)
			}
			continue
		}

		switch ch {
		case '"':
			inQuotes = true
		case ',':
			values = append(values, current.String())
			current.Reset()
		default:
			current.WriteByte(ch)
		}
	}

	if escaped || inQuotes {
		return nil, fmt.Errorf("invalid PostgreSQL array literal %q", src)
	}

	values = append(values, current.String())
	return values, nil
}

func generatedFormatPostgresTextArray(values []string) string {
	if len(values) == 0 {
		return "{}"
	}

	encoded := make([]string, len(values))
	for i, value := range values {
		escaped := strings.ReplaceAll(value, "\\", "\\\\")
		escaped = strings.ReplaceAll(escaped, "\"", "\\\"")
		encoded[i] = "\"" + escaped + "\""
	}

	return "{" + strings.Join(encoded, ",") + "}"
}
`
